# Generated by Django 4.0 on 2021-12-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('quanitity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('guide', models.TextField()),
                ('picture', models.ImageField(upload_to='Products')),
                ('type', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('quanitity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('guide', models.TextField()),
                ('picture', models.ImageField(upload_to='Products')),
                ('type', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('quanitity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('guide', models.TextField()),
                ('picture', models.ImageField(upload_to='Products')),
                ('type', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
