# Generated by Django 4.0 on 2021-12-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    def defaultUser(apps,schema_editor):
        User = apps.get_model('authentication','User')
        User.objects.create_user(
            firstname="admin",
            lastname = "admin",
            email = "admin@gmail.com",
            password = "adminn",
            phoneNumber = "01111111111",
            is_active=True,
            is_staff = True,
            is_superuser = True,
            )


    dependencies = [
        ('authentication', '0001_initial'),
    ] 

    operations = [
        migrations.RunPython(defaultUser),
    ]
